blank_issues_enabled: true
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/Theopsguide/gemini-code-flow/discussions
    about: For general questions, ideas, and community discussion
  - name: 📚 Documentation
    url: https://github.com/Theopsguide/gemini-code-flow/blob/main/README.md
    about: Check out our documentation and guides